### ISSUE TITLE
This library does not currently parse my .msh files

### ISSUE THREAD

**Issue by haoxl3** [amandaghassaei/msh-parser#1]
my .msh files is:https://github.com/haoxl3/vtkData
I got error:
<img width="1210" alt="image" src="https://github.com/amandaghassaei/msh-parser/assets/15046133/a578bfaf-a96c-4301-91ab-e76f99ecc592">

**Comment by amandaghassaei** [comment]
just added ascii support to master, will release to npm in a sec.  can I include your file in my tests?  or better, do you have a smaller ascii msh file that I can add to the tests?

**Comment by haoxl3** [comment]
> just added ascii support to master, will release to npm in a sec. can I include your file in my tests? or better, do you have a smaller ascii msh file that I can add to the tests?

Sorry, I don't have smaller ascii msh file, you can use https://github.com/haoxl3/vtkData

**Comment by amandaghassaei** [comment]
ok I've just made a small fix and updated main and the npm package (v1.5.1).  do you know what program was used to generate your msh file?
