### ISSUE TITLE
live demo cannot display the data of my.msh format file yet

### ISSUE THREAD

**Issue by haoxl3** [amandaghassaei/msh-parser#2]
[live demo](https://apps.amandaghassaei.com/msh-parser/demo/) cannot display the data of my.msh format file yet, my .msh file is [here](https://github.com/haoxl3/vtkData/blob/main/01_strocchi_LV.msh)

**Comment by amandaghassaei** [comment]
just fixed this (you may need to clear your cache to get the latest demo).  Your file take ~30s to load, but appears to be working:
<img width="780" alt="Screen Shot 2023-09-20 at 9 04 14 AM" src="https://github.com/amandaghassaei/msh-parser/assets/3218981/8280ca40-659d-4c0b-aeb8-798cbd58fc11">
